#! /usr/bin/perl

# highest_power

use v5.14; use warnings; no warnings qw<uninitialized>;

my ($serial_num) = @ARGV;
my (@sum, %max);
for my $x (1 .. 300)
{
  my $rack_id = $x + 10;
  for my $y (1 .. 300)
  {
    my $power = ($rack_id * $y + $serial_num) * $rack_id / 100 % 10 - 5;
    $sum[$x][$y] = $power + $sum[$x][$y - 1] + $sum[$x - 1][$y] - $sum[$x - 1][$y - 1];
  }
}
for my $x (1 .. 298)
{
  for my $y (1 .. 298)
  {
    my $power = $sum[$x + 2][$y + 2] - $sum[$x + 2][$y - 1] - $sum[$x - 1][$y + 2] + $sum[$x - 1][$y - 1];
    %max = (power => $power, pos => "$x,$y") if !defined $max{power} || $power > $max{power};
  }
}
say $max{pos};
