#! /usr/bin/perl

# region_size

use v5.14; use warnings; use List::AllUtils qw<minmax>;

my @coord = map { [/(\d+)/g] } <>;
my @dim;
for my $i (0..1)
{
  @{$dim[$i]}{qw<min max>} = minmax map { $_->[$i] } @coord;
}
my $region_size;
for my $x ($dim[0]{min} .. $dim[0]{max})
{
  POS: for my $y ($dim[1]{min} .. $dim[1]{max})
  {
    my $total;
    foreach (@coord)
    {
      next POS if ($total += abs ($_->[0] - $x) + abs ($_->[1] - $y)) >= 10e3;
    }
    $region_size++;
  }
}
say $region_size;
