#! /usr/bin/perl

# region_size

use v5.14; use warnings; use List::AllUtils qw<minmax>;

my %dim;
my @coord = map {
  /(?<x>\d+), (?<y>\d+)/ or die "Unexpected input: $_";
  @{$dim{$_}}{qw<min max>} = minmax $+{$_} + 0, values %{$dim{$_}} for qw<x y>;
  {x => $+{x}, y => $+{y}};
} <>;

my $region_size;
for my $x ($dim{x}{min} .. $dim{x}{max})
{
  POS: for my $y ($dim{y}{min} .. $dim{y}{max})
  {
    my $total;
    foreach (@coord)
    {
      next POS if ($total += abs ($_->{x} - $x) + abs ($_->{y} - $y)) >= 10e3;
    }
    $region_size++;
  }
}
say $region_size;
