#! /usr/bin/perl

# sorted

use v5.14; use warnings; use List::AllUtils qw<first>;

my %depends;
while (<>)
{
  /Step (.) .* step (.)/g or die;
  $depends{$1} //= '';
  $depends{$2} .= $1;
}

my $order;
while (%depends)
{
  my $now = first { $depends{$_} eq '' } sort keys %depends;
  $order .= $now;
  delete $depends{$now};
  $depends{$_} =~ s/$now// foreach keys %depends;
}
say $order;
