#! /usr/bin/perl

# risk_level

use v5.14;
use warnings;
use List::AllUtils qw<sum>;

my ($depth, $target_x, $target_y) = map { /(\d+)/g } <>;
my $risk;
my @erosion = map { ($_ * 16807 + $depth) % 20183 } 0 .. $target_x;
for my $y (1 .. $target_y + 1)
{
  $risk += sum map { $_ % 3 } @erosion;
  my @prev_erosion = @erosion;
  @erosion = ();
  my $geological_index = $y * 48271;
  for my $x (1 .. $target_x + 1)
  {
    push @erosion, ($geological_index + $depth) % 20183;
    $geological_index = $erosion[-1] * $prev_erosion[$x - 1];
    $geological_index = 0 if $x == $target_x && $y == $target_y;
  }
}
say $risk;
