#! /usr/bin/perl

# shortest_removal

use v5.20;
use warnings;
use experimental qw<signatures>;
use List::AllUtils qw<min>;

sub collapse($p) { 1 while $p =~ s/(?i:(.)\1)(?<=[a-z][A-Z]|[A-Z][a-z])//g; $p }

chomp (my $polymer = collapse <>);
say length $polymer;
say min map { length collapse($polymer =~ s/$_//igr) } 'a' .. 'z';
