#! /usr/bin/perl

# part1

use v5.14;
use warnings;
use List::AllUtils qw<sum>;

my ($max) = @ARGV;
my $recipe  = '37';
my @cooking = (0, 1);
while (length $recipe <= $max + 10)
{
  $recipe .= sum map { substr $recipe, $_, 1 } @cooking;
  $_ = ($_ + (substr $recipe, $_, 1) + 1) % length $recipe for @cooking;
}
say substr $recipe, $max, 10;
