#! /usr/bin/perl

# marbles_score

use v5.14; use warnings; use List::AllUtils qw<max>;

my ($NumPlayers, $MaxMarble) = @ARGV;
my @circle = (0);
my $current_marble = 0;
my @score;
for my $turn (1 .. $MaxMarble) {
  if ($turn % 23)
  {
    $current_marble = ($current_marble + 1) % @circle + 1;
    splice @circle, $current_marble, 0, $turn;
  }
  else
  {
    $current_marble = ($current_marble - 7) % @circle;
    $score[$turn % $NumPlayers] += $turn + splice @circle, $current_marble, 1;
  }
}
no warnings qw<uninitialized>;
say max @score;
