#! /usr/bin/perl

# marbles_score

use v5.14; use warnings;

my ($Players, $Marbles) = @ARGV;
my @circle = (0);
my $player = 1;
my $current_marble = 0;
for my $turn (1 .. $Marbles) {
  $current_marble = ($current_marble + 1) % @circle + 1;
  splice @circle, $current_marble, 0, $turn;
  say "@circle";
}
